### ISSUE TITLE
osx 10.10 on sbcl, make bundle on markedit fails at archive step

### ISSUE THREAD

**Issue by jkordani** [ceramic/ceramic#10] opened 2015-07-31 20:00 UTC
after needing to modify electron to delete a dangling symbolic link inside the project (bug resolved upstream), bundle fails at archive step with:

electron/Electron.app/Contents/Frameworks/Squirrel.framework/Versions/Current/Modules/module.modulemap has too many characters in it.

in   0: ((:METHOD ARCHIVE:CREATE-ENTRY-FROM-PATHNAME (ARCHIVE:TAR-ARCHIVE T)) #<unavailable argument> #P"electron/Electron.app/Contents/Frameworks/Squirrel.framework/Versions/Current/Modules/module.modulemap"..

additionally, if I simply browse into the working directory and run the markedit application, it just hangs and the cpu spins up.

**Comment by jkordani** [comment] 2015-07-31 20:01
also noteworthy, the ceramic interactive demo works flawlessly.

**Comment by eudoxia0** [comment] 2015-08-05 21:39
That's weird. Does trying to build the archive with native `tar` produce the same error?

**Comment by jkordani** [comment] 2015-08-06 14:03
do you mean, skip doing the archiving in CL and shell out to tar for this step?

In debugging this and issue 12, I comment out all of the code that copies electron into the working dir and creates an archive.  I copy electron into working by hand and then try to run the applications.  In both cases (bundling markedit and bundling the ceramic hello world example) the executable pauses at "waiting for startup" and then spins up to 100% cpu.

**Comment by glider-gun** [comment] 2015-08-09 09:18
I'll write here instead of at #12.
current progress:
- `electron:binary-pathname` are applied twice in `ceramic:define-entry-point` (once explicitly, once inside `ceramic.electron:start-process`), so deleted former. This seems the cause of @jkordani's cpu spinning up to 100%.
- for now fallbacked copying and tar-upping to unix binary (both to avoid symbolic link problem)
- loading `cl-locale` somehow causes problem in `buildapp` process, so I slightly modified cl-locale.asd. I don't know now if it can be fixed from ceramic side, or cl-locale should be fixed.

It seems generated tar files are working, although I can't properly close app (closing application window doesn't stop command line side). Is it ok?

ceramic files:

``` diff
diff --git a/src/ceramic.lisp b/src/ceramic.lisp
index bfe63b1..4e507b7 100644
--- a/src/ceramic.lisp
+++ b/src/ceramic.lisp
@@ -299,28 +299,30 @@
   (let ((entry-point (intern (symbol-name system-name)
                              (find-package :ceramic-entry)))
         (arguments (gensym))
-        (electron-directory (gensym))
-        (binary (gensym)))
+        (electron-directory (gensym)))
     `(defun ,entry-point (,arguments)
        (declare (ignore ,arguments))
        ;; Start the executable-relative Electron process
        (let* ((*releasep* t)
-              (,electron-directory (executable-relative-pathname #p"electron/"))
-              (,binary (binary-pathname ,electron-directory
-                                        :operating-system *operating-system*))
+              (,electron-directory (print  (executable-relative-pathname #p"electron/")))
               (*process*
                 (progn
                   (format t "~&Starting Electron process...")
-                  (ceramic.electron:start-process ,binary
-                                                  :operating-system *operating-system*))))
+                  (ceramic.electron:start-process (print ,electron-directory)
+                                                  :operating-system *operating-system*)
+         )))
          (flet ((wait-until-startup ()
                   (let ((output (process-stdout)))
                     (loop until (search "READY" output) do
                       (let ((new-output (process-stdout)))
-                        (setf output (concatenate 'string output new-output)))))
+                        (setf output (concatenate 'string output new-output))
+           (print output)  ; => "env: /private/tmp/Users/glidergun/.ceramic/working/./electron/Electron.app/Contents/MacOS/Electron.app/Contents/MacOS/Electron: No such file or directory" before fixing twice binary-pathname
+           (sleep 1))))
                   ;; Clear all stdout
                   (process-stdout)))
            (format t "~&Waiting for startup...")
+      (finish-output)
            (wait-until-startup)
            (format t "~&Electron process started.")
            (handler-case
diff --git a/src/util.lisp b/src/util.lisp
index 538da86..e516e4d 100644
--- a/src/util.lisp
+++ b/src/util.lisp
@@ -31,19 +31,24 @@
 (defun copy-directory (source destination)
   "Copy everything under source to destination."
   (ensure-directories-exist destination)
-  (fad:walk-directory source
-                      #'(lambda (pathname)
-                          (unless (equal pathname source)
-                            (let* ((relative-path (subtract-pathname source pathname))
-                                   (target (merge-pathnames relative-path
-                                                            destination)))
-                              (if (uiop:directory-pathname-p pathname)
-                                  ;; Ensure an equivalent directory exists
-                                  (ensure-directories-exist target)
-                                  ;; Copy the absolute source file to the target
-                                  (uiop:copy-file pathname target)))))
-                      :directories :breadth-first
-                      :follow-symlinks nil)
+  (external-program:run #P"/bin/cp"
+           (print  (list "-r"
+                     source
+                     destination)))
   destination)

 (defun zip-up (directory output)
@@ -74,13 +79,17 @@
 (defun tar-up (directory output)
   "Create a tar archive from the contents of a directory."
   (let ((*default-pathname-defaults* directory)
-        (files (list)))
-    (flet ((relativize (pathname)
-             (subtract-pathname *default-pathname-defaults* pathname)))
-      (cl-fad:walk-directory directory
-                             #'(lambda (pathname)
-                                 (push (relativize pathname) files))))
-    (archive::create-tar-file output files)
+   )
+    (external-program:run "/usr/bin/tar"
+            (list "cvf" output directory))
     output))

 (defun ensure-executable (pathname)
```

cl-locale.asd:

``` diff
  :long-description
  #.(with-open-file (stream (merge-pathnames
                             #p"README.markdown"
                             (or *load-pathname* *compile-file-pathname*))
                            :if-does-not-exist nil
+               :external-format :UTF-8
                            :direction :input)
```

**Comment by glider-gun** [comment] 2015-08-12 01:12
`cl-locale` problem seems to occur because LANG environment variable was not set. By setting LANG to "en_US.UTF-8" suppressed it.

**Comment by eudoxia0** [comment] 2015-08-12 23:16
I like the solution of using /bin/tar and /bin/cp on Unix, but we must still provide those functions for Windows users.

**Comment by glider-gun** [comment] 2015-08-19 00:29
I made pull request that uses unix binaries on OS X.

**Comment by eudoxia0** [comment] 2015-08-19 23:31
@jkordani can you try this again with the master?

**Closed as completed** 2016-03-25 17:12 UTC
Labels: bug

**Comment by jkordani** [comment] 2016-03-25 19:54
Sorry, Lost access to my mac machine, when I get back on one I'll retry it all.

**Comment by eudoxia0** [comment] 2016-03-25 20:01
Ok, great!
